### ISSUE TITLE
Penyusunan Pemain

### ISSUE THREAD

**Issue by rafiadji** [rafiadji/graphicFinal#2]
Penyusunan pemain ke lapangan sesuai penentuan posisi

**Comment by rafiadji** [comment]
@goFrendiAsgard

**Comment by goFrendiAsgard** [comment]
Apa yang mau ditanyakan? Coba jelaskan secara lebih spesifik

**Comment by rafiadji** [comment]
ini hanya task saja pak semnetara ini masih belum ada yg di tanyakan
